
Path:
  ori_path: E:/data/myspine-dataset/2D-morph-seg # dataset root folder
  oriimg_path: "" #  defalt  ori_path/img    stroe large img eg 512*512
  orilabel_path: "" # defalt  ori_path/label  stroe label for img eg 512*512
  
  exp_path: "../DATA/2d_ins_wnet2"
  crop_path: "../DATA/2d_seg/data" #  defalt exp_path/data/

  img_path: "" #  defalt exp_path/data/imgcrop    store small img eg 128*125
  label_path: "" # defalt  exp_path/data/labelcrop will crop from whole img , eg from 512 to 256,128 , see input size

  log_path: ""  #  defalt  exp_path/log error , tensorboard score log dir,configure dir/log path
  model_path : "" #  defalt  exp_path/data/model, configure dir/model path
  model_save_path: "DATA/model/2Dtorchune3/seg/best.ckpt" # no use
  

  save_suffix: "-ins" # -border todo : -den -spine
  label_suffix: "-seg"

  filetype: ".tif"

Data:
  axes: 'yx' # change to zyx ,todo
  z_factor: 2.0 # z spacing / x spancing ,x spacing=y spacing,todo
  input_sizez: 1  # Input depth ,z
  input_sizexy: 256   # 256*256,Input feature width/height,for crop generate img data
  num_class: 3 # include zero background
  inputchannel: 1 # 1: grayscale,todo
  partion : [0.9,0.1,0.0] # train,valid,test+=1
  c_val : "auto" # background value
  data_augmentation: #no use todo
    translate: false
    flip: true
    rotate: true
    probability: 0.3
    affine: 0.3

    
Training:

  task_type: "ins"

  Network:
    name : "wnet" # unet2d unet++  ...
    kwargs: 
      input_channel: 1
      num_class : 3
      unet_dim : 64
      dis2emb_channels : 2
      emb_channels : 6
      seeds_thres: 0.6
      seeds_min_dis: 5
      similarity_thres : 0.7
    

    
  loss_type:
    name: "Wnet_loss" 
    kwargs: 
      radius : 10
      w_inst: 1 #inter
      w_var: 5 #intra
      w_seed: 1
    


      
  Metrics:
    name : "miou_wnet"
    kwargs: 
      ignore_labels: [0,1]

    
  batch_size: 8
  keep_top: 10
  loss_plot_epoch: 1
  visual_epoch : 1
  mAP_epoch : 10
  cls_weight: [1,1,1]
  epochs: 500
  optimizer_name: "Adam" # supports [Adam, Adagrad, RMSProp]
  learning_rate: 0.001
  denovo : False
  seed: 42

